### PR TITLE
Support specify CPU cores and Memory restricts for driver

### PR DESCRIPTION
**Pull request by duyanghao**
Signed-off-by: duyanghao <1294057873@qq.com>

## What changes were proposed in this pull request?

Support specify CPU cores and Memory restricts for driver:
support spark driver parameters:`spark.driver.memory` and `spark.driver.cores`

## How was this patch tested?

Manual tests were successful.Example is as follows:

kubectl describe pods/spark-driver:
```
Containers:
  spark-kubernetes-driver:
    Container ID:	docker://08f343477affe77690ba0aa43deabc0adaaa0be57b795a7f75378176c431883b
    Image:		xxx/xxx/spark-driver-app:v0.2-test5
    Image ID:		docker://sha256:4200b209ad2d1c604e18f14b967592b25c2063d21cea637a77b971435ff38909
    Port:		
    Limits:
      cpu:	2
      memory:	3456M
    Requests:
      cpu:		2
      memory:		3072M
```

submit command:
```
--conf spark.driver.memory=3G
--conf spark.driver.cores=2
```

### CODE REVIEW

**Comment by foxish** [comment]
This LGTM.

**Comment by tnachen** [comment]
LG too

**Comment by foxish** [comment]
Thanks @duyanghao

**Comment by ash211** [comment]
Thanks for the PR @duyanghao !

**Pull request merged**
