### PR TITLE
Build with sbt and fix scalastyle checks.

### PR DESCRIPTION
**Pull request by lins05**
I want to build the project with sbt mainly because i want to set it up with [ensime](https://github.com/ensime/ensime-server/).

However, the build with sbt (`./build/sbt -Pkubernetes -Phadoop-2.6 -Pkubernetes-integration-tests -Pmesos -Pyarn -Phive compile test:compile`) failed with scalastyle check errors:

```sh
$ ./dev/scalastyle
Scalastyle checks failed at following occurrences:
[error] /data/github/spark/spark-k8s/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/rest/kubernetes/v2/ResourceStagingServerSslOptionsProviderSui
te.scala:99: File line length exceeds 100 characters
[error] /data/github/spark/spark-k8s/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/SSLUtils.scala:23:0: import.ordering.wrongOrderInG
roup.message
[error] (kubernetes/test:scalastyle) errors exist
[error] Total time: 10 s, completed Apr 23, 2017 3:34:14 PM
```

### CODE REVIEW

**Review by mccheah — APPROVED** [review]
Looks great, thanks!

**Comment by lins05** [comment]
@mccheah Can we merge this one?

**Comment by foxish** [comment]
This LGTM. Merging after tests pass. Thanks @lins05

**Comment by foxish** [comment]
Thanks @lins05

**Pull request merged**
