### PR TITLE
Fill in the namespace for all resource specs.

### PR DESCRIPTION
**Pull request by mccheah**
The use case for this is subtle, but the authn/authz APIs that can be customized for any given Kubernetes cluster, are only given the resource object's spec as-is. If the namespace is not provided in the spec, the model sent around to these authentication endpoints won't know what the namespace is on the resource, which can be critical information for them to make decisions in admission control. The API server itself knows the namespace since it's encoded in the request URI,but other components that receive the resource object model need this information to be provided in the spec.

### CODE REVIEW

**Comment by ash211** [comment]
Is there an upstream ticket for this?  Sounds like a change in the apiserver to forward the inferred namespace to the authz server would make this unnecessary?

**Comment by mccheah** [comment]
@foxish is there a way upstream Kubernetes could fill this in for Authz if it's missing in the original resource object?

**Comment by foxish** [comment]
Are you using a custom authorization plugin? The `authorizer.Attributes` object should allow you to get the namespace associated with that request I think.

**Comment by mccheah** [comment]
We addressed this internally

**Comment by ash211** [comment]
We are using a custom authorization plugin, and have patched our internal fork of kubernetes to send additional info where it wasn't before.  I'm not sure how applicable it is to the wider kubernetes community though as we've changed how that works a bit, so am closing this PR.

@jlz27 who chatted with you about ingress a few weeks ago might have more details to share.

**Comment by jlzhao27** [comment]
Ya this was due to a bug in our custom webhook based admission controller. We forked k8s apiserver to add pluggable support for admission control and did not pass the path based parameters from `Attributes`.

**Pull request closed without merging**
