### PR TITLE
Update pom to v0.3.1 for the new 2.1 release

### PR DESCRIPTION
**Pull request by liyinan926**
For #416.

### CODE REVIEW

**Comment by liyinan926** [comment]
rerun unit tests please

**Comment by erikerlandson** [comment]
I'm wondering if we should call it 0.3.1, since it's a bug-fix release

**Comment by liyinan926** [comment]
I discussed with @foxish offline and he said 0.4 would be fine. I agree 0.3.1 is better since it's a bug fix release. Let me update the PR to use 0.3.1.

**Comment by foxish** [comment]
I don't have strong opinions on this. If it's minor enough that we think
0.3.1 captures it well, then let's do that.

**Comment by liyinan926** [comment]
Updated to 0.3.1.

**Comment by foxish** [comment]
PTAL @mccheah @ash211 @kimoonkim

**Comment by foxish** [comment]
LGTM, merge on green unless there are objections.

**Review by ash211 — APPROVED** [review]

**Pull request merged**
