### PR TITLE
Pull component readiness logic to another class

### PR DESCRIPTION
**Pull request by mccheah**
Pull out waiting for components to be ready to a separate class.

Part of #109

### CODE REVIEW

**Comment by mccheah** [comment]
Soft dependency on #123 to fix merge conflicts as we go along.

**Comment by iyanuobidele** [comment]
At first look: 
This is awesome! I really love how you've pulled out and separated the different logics in the client. This will definitely make unit testing easier.

I'll review them (the refactor PRs) more closely tomorrow.

**Comment by ash211** [comment]
Now that the SSL refactoring PR is in this one is ready for rebase and separation from the Ingress PR

**Comment by mccheah** [comment]
This seems difficult to rebase though - I'm fine just re-building this from scratch, especially after the code churn from #147 .

**Pull request closed without merging**
