### PR TITLE
add mvn install directions

### PR DESCRIPTION
**Pull request by luck02**
From: https://github.com/apache-spark-on-k8s/spark/issues/380

Current build instructions left me with issues noted above.

## What changes were proposed in this pull request?

Better documentation on building Apache-Spark-on-K8s

## How was this patch tested?

Manual tests.  I'm not sure if this issue is just my machine (Seems unlikely).  in any case I'm not sure if the build steps should just be install / build OR if there should be a comment saying: "if you run into this big hairy looking dependencies issues then do this"  It's probably fine either way.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by foxish** [comment]
I'd rather just replace the compile instruction entirely and just have the user do an install. WDYT @mccheah?

**Comment by erikerlandson** [comment]
@foxish, going straight to `install` seems sensible for user instructions

**Comment by luck02** [comment]
I have no opinions, just want to help straighten out the documentation 👍

**Comment by erikerlandson** [comment]
Possibly `package` as an alternative - I think that is the most direct way to getting to the point of being able to run `./bin/spark-submit` from the user's source repo

**Comment by ash211** [comment]
Thanks for the suggestion @luck02 !  I just merged a very similar change to this one at #423 so I'm going to close this PR.

Appreciate the contribution to helping onboard more people to this project!

**Pull request closed without merging**
