### PR TITLE
Update upstream docs [WIP]

### PR DESCRIPTION
**Pull request by foxish**
Draft of what we should include in upstream documentation.

http://spark.apache.org/docs/latest/submitting-applications.html links back to this section. 
Any other places where you think it may be worth mentioning?
@ash211 @mccheah

### CODE REVIEW

**Comment by foxish** [comment]
Maybe we should have a running-on-kubernetes page also upstream? 
@tnachen PTAL. What would be most appropriate here?

**Comment by ash211** [comment]
Made a minor change, with that I think this is good to send upstream @foxish

**Comment by tnachen** [comment]
Did you try building the docs and see if Kubernetes also shows up in the header menu "Deploying"?

**Comment by tnachen** [comment]
Also adding it to the index page: https://spark.apache.org/docs/latest/
You can search for YARN and see there is a listing there.

**Comment by foxish** [comment]
Addressed @tnachen's comments and opened https://github.com/apache/spark/pull/17522
Closing this

**Pull request closed without merging**
