### PR TITLE
Updated developer doc to include a install step for first time compilation

### PR DESCRIPTION
**Pull request by liyinan926**
Added the missing install step for those who compile the Kubernetes core implementation module for the first time.

### CODE REVIEW

**Comment by erikerlandson** [comment]
This seems inconsistent with maven docs, which [claim](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Build_Lifecycle_Basics) that `install` implies the `compile` goal.  Why does `install` need to be run first?

> (install) executes each default life cycle phase in order (validate, compile, package, etc.), before executing install. You only need to call the last build phase to be executed, in this case, install:

**Comment by liyinan926** [comment]
It seems `compile` may complain about missing dependencies if this is the first time to try to compile.

**Comment by erikerlandson** [comment]
it definitely does, although I've been confused about why for some time.

**Comment by foxish** [comment]
I usually run `package` in my general workflow, which should do the validate and compile as well. 
We could just keep that. The `install` step is useful for speeding up subsequent builds.

I don't think we need to suggest the `mvn compile` separately at all.

**Comment by mccheah** [comment]
If the `-am` flag is provided to the build reactor, the dependencies should be built and also available for use in the downstream projects. However this behavior has been inconsistent for me as of late and I haven't explored as to why.

**Comment by ash211** [comment]
This is now the second time someone has suggested adding this to the docs (earlier was https://github.com/apache-spark-on-k8s/spark/pull/382) so clearly people would find it helpful.

I'm going to merge this PR since it's more current and comprehensive than the other one, and we can figure out the resolution issues separately

**Pull request merged**
