### PR TITLE
Fixup Dockerfile for driver and excutor

### PR DESCRIPTION
**Pull request by hustcat**
Fixup #209 .

### CODE REVIEW

**Comment by ash211** [comment]
rerun integration test please

**Comment by mccheah** [comment]
How do the integration tests pass without this fix? The integration tests build the docker images as well.

**Comment by ash211** [comment]
@hustcat did you get a chance to think about @mccheah's question?

**Comment by hustcat** [comment]
@ash211 @mccheah Sorry about the delay reply, I will check it later:)

**Comment by hustcat** [comment]
It seems that  `examples` directory is created by [`integration-tests`](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/resource-managers/kubernetes/integration-tests/pom.xml#L143) project, so integration tests can pass before this PR . However, there is not `examples`  directory  for [docker-minimal-bundle](https://github.com/apache-spark-on-k8s/spark/tree/branch-2.1-kubernetes/resource-managers/kubernetes/docker-minimal-bundle) project. Should we discard this PR?

**Comment by mccheah** [comment]
Right - integration tests need some jars mounted into the image. I recall choosing the `examples` directory thinking we would want to add the examples into the "real" image as well.

I believe we don't want `docker-minimal-bundle` itself to be building the examples - doing so might increase build time since now integration tests would depend on building all of the example projects. However, real distributions should include the examples directory.

@hustcat what directory are you building the Docker images from? And what command do you use? For a real Spark distribution I would expect this to work:

    tar -xzvf spark.....tgz
    cd spark
    docker build -t spark-driver:latest -f dockerfiles/driver/Dockerfile .

**Comment by hustcat** [comment]
@mccheah, I build `docker-minimal-bundle` project, and run `docker build` in the `target/spark-docker-minimal-bundle_2.11-2.1.0-k8s-0.1.0-SNAPSHOT-driver-docker-dist` directory:

```
# ls resource-managers/kubernetes/docker-minimal-bundle/target/spark-docker-minimal-bundle_2.11-2.1.0-k8s-0.1.0-SNAPSHOT-driver-docker-dist
Dockerfile  bin  conf  jars  sbin
```

Yeah, I build success from the complete distribution `spark-...-bin.tgz`.

I'll close this PR, and I think we should add this to the document.

**Pull request closed without merging**
