### PR TITLE
Adding restart policy fix for v2

### PR DESCRIPTION
**Pull request by foxish**
Fixes https://github.com/apache-spark-on-k8s/spark/issues/302

cc @apache-spark-on-k8s/contributors

### CODE REVIEW

**Comment by foxish** [comment]
rerun integration test please

**Review by ash211 — APPROVED** [review]
@mccheah ?

**Comment by mccheah** [comment]
Looks fine. Merging.

**Comment by mccheah** [comment]
Does this need to be on executors also?

**Comment by foxish** [comment]
Hmm.. the executors restart and try to reconnect, which is recovery behavior we want in that case. I don't think there is a reason to prevent executor pods restarting after errors. If it is a transient error, it will eventually succeed, and if it isn't, we should fail the job after a threshold. 

cc @varunkatta

**Pull request merged**
