### PR TITLE
Added log4j config for k8s unit tests

### PR DESCRIPTION
**Pull request by lins05**

### CODE REVIEW

**Comment by mccheah** [comment]
I'm surprised the core Spark testing framework doesn't give us something reasonable here. Are we perhaps not configuring something like core Spark is?

**Comment by lins05** [comment]
@mccheah I don't think so. It's configured in all other modules.

```sh
spark-master $ git grep -l target/unit-tests.log
R/log4j.properties
common/network-common/src/test/resources/log4j.properties
common/network-shuffle/src/test/resources/log4j.properties
core/src/test/resources/log4j.properties
external/flume-sink/src/test/resources/log4j.properties
external/flume/src/test/resources/log4j.properties
external/kafka-0-10-sql/src/test/resources/log4j.properties
external/kafka-0-10/src/test/resources/log4j.properties
external/kafka-0-8/src/test/resources/log4j.properties
external/kinesis-asl/src/main/resources/log4j.properties
external/kinesis-asl/src/test/resources/log4j.properties
graphx/src/test/resources/log4j.properties
launcher/src/test/resources/log4j.properties
mllib/src/test/resources/log4j.properties
repl/src/test/resources/log4j.properties
resource-managers/yarn/src/test/resources/log4j.properties
sql/catalyst/src/test/resources/log4j.properties
sql/core/src/test/resources/log4j.properties
sql/hive/src/test/resources/log4j.properties
streaming/src/test/resources/log4j.properties```

**Comment by lins05** [comment]
ping @mccheah

**Review by ash211 — APPROVED** [review]
LGTM will merge when build is green

**Pull request merged**
