### PR TITLE
Sync hdfs-kerberos-support to branch-2.2-kubernetes

### PR DESCRIPTION
**Pull request by kimoonkim**
Note the target branch is `hdfs-kerberos-support`. There were a few conflicts in imports and constants.

@ifilonenko When you merge this, please avoid squashing so the history can show original commits. Maybe "rebase merging" is the right option to use?

### CODE REVIEW

**Comment by kimoonkim** [comment]
rerun unit tests please

**Comment by ifilonenko** [comment]
This is good to merge because unit-tests issues are solved with #414

**Comment by kimoonkim** [comment]
Thanks @ifilonenko. Merging into hdfs-kerberos-support.

**Comment by kimoonkim** [comment]
Manually pushed to hdfs-kerberos-support. Closing.

**Pull request merged**
