### PR TITLE
Parse results of minikube status more rigorously

### LINKED ISSUE #96: Exception when running integration tests with minikube upgrade available
Saw this while running integration tests:

`build/mvn -B integration-test -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite`:

```
Exception encountered when invoking run on a nested suite - Unknown status There is a newer version of minikube available (v0.16.0).  Download it here: *** ABORTED ***
  java.lang.IllegalStateException: Unknown status There is a newer version of minikube available (v0.16.0).  Download it here:
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$$anonfun$getMinikubeStatus$2.apply(Minikube.scala:69)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$$anonfun$getMinikubeStatus$2.apply(Minikube.scala:69)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$.getMinikubeStatus(Minikube.scala:69)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$.startMinikube(Minikube.scala:51)
  at org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite.beforeAll(KubernetesSuite.scala:82)
  at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
  at org.apache.spark.SparkFunSuite.beforeAll(SparkFunSuite.scala:31)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
  at org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite.org$scalatest$BeforeAndAfter$$super$run(KubernetesSuite.scala:46)
```

Should either set `minikube config set WantUpdateNotification false` (https://github.com/kubernetes/minikube/blob/master/pkg/minikube/notify/notify.go#L68) or parse the results more rigorously

### PR DESCRIPTION
**Pull request by ash211**
Fixes #96 

Prior code assumes the minikubeVM status line is always the first row output
from minikube status, and it is not when the version upgrade notifier prints
an upgrade suggestion message.

### CODE REVIEW

**Comment by kimoonkim** [comment]
+1. I was puzzled by the version update notifier message a few times.

**Comment by mccheah** [comment]
It would be nice to filter the update notification everywhere. For example, it still prints when you run `minikube ip` or `minikube start`.

Alternatively, getting Minikube to point to the `config.json` which has the appropriate notification flag turned off would be ideal. Then we can skip this check entirely.

**Comment by ash211** [comment]
@mccheah I added a filter for `minikube ip` since that can break the output parsing, but didn't do anything for `minkube start` since unexpected output there wouldn't break anything.

I'd rather not invest too much in fixing minikube since my personal belief is that we should support running tests against any k8s serverapi, not just minikube.

**Comment by mccheah** [comment]
Looks fine - will merge.

**Pull request merged**
