### PR TITLE
Use "extraScalaTestArgs" to pass extra options to scalatest.

### PR DESCRIPTION
**Pull request by lins05**
## What changes were proposed in this pull request?

Because the "argLine" option of scalatest is set in pom.xml and we can't
overwrite it from the command line.

Ref apache-spark-on-k8s/spark#37

## How was this patch tested?

When I use this option to set `spark.docker.test.persistMinikube` to `true`, the minikube vm wasn't deleted after the integration tests, which is expected.

```sh
build/mvn -Pkubernetes -Pkubernetes-integration-tests \
          -pl resource-managers/kubernetes/integration-tests -am \
          -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite \
          -DextraScalaTestArgs=-Dspark.docker.test.persistMinikube=true \
          integration-test
```

### CODE REVIEW

**Review by ash211 — APPROVED** [review]
This seems right, though I'm not especially familiar with Maven.

**Comment by ssuchter** [comment]
This is a fine way to do it, but I wonder if a name like "extraScalaTestArgs" would be a clearer name.

**Comment by lins05** [comment]
@ssuchter Good suggestion. I've updated the name.

**Comment by ssuchter** [comment]
+1 to merge.

**Pull request merged**
