### PR TITLE
Fast forward to upstream master

### PR DESCRIPTION
**Pull request by mccheah**
Proposing a PR to fast-forward to the head of upstream master, but open to discussing if fast-forwards should just be done without review next time. @foxish

### CODE REVIEW

**Comment by foxish** [comment]
I'm in favor of just doing fast forwards without review. 
I don't expect that upstream commits will change anything substantially for us in future, other than the commit which reorganizes the schedulers into `resource-managers/`.

**Comment by mccheah** [comment]
Ok - will merge this one but in the future will just push directly.

**Comment by mccheah** [comment]
Actually on second thought I'll push directly for this one as well - Github will squash the commits and we don't want to lose the history that way.

**Comment by foxish** [comment]
SGTM

**Pull request closed without merging**
