### PR TITLE
Update poms for 2.2 release 0.4.0

### PR DESCRIPTION
**Pull request by foxish**
xref: https://github.com/apache-spark-on-k8s/spark/issues/499

cc @apache-spark-on-k8s/contributors @ifilonenko @liyinan926 @erikerlandson

### CODE REVIEW

**Comment by liyinan926** [comment]
LGTM.

**Comment by foxish** [comment]
Verified by running integration tests manually (because of https://github.com/apache-spark-on-k8s/spark/issues/509)
All looking good.

```
- Run PySpark Job on file from SUBMITTER with --py-files
- Run PySpark Job on file from CONTAINER with spark.jar defined
- Simple submission test with the resource staging server.
- Enable SSL on the resource staging server
- Use container-local resources without the resource staging server
- Dynamic executor scaling basic test
- Use remote resources without the resource staging server.
- Mix remote resources with submitted ones.
- Use key and certificate PEM files for TLS.
- Use client key and client cert file when requesting executors
- Added files should be placed in the driver's working directory.
- Setting JVM options on the driver and executors with spaces.
- Submit small local files without the resource staging server.
- Use a very long application name.
```

**Comment by ifilonenko** [comment]
LGTM, please run e2e via Jenkins after #509 is resolved before merging

**Comment by ssuchter** [comment]
Let's run the e2e again, I think that #509 is resolved.

**Comment by foxish** [comment]
rerun integration tests please

**Pull request merged**
