### PR TITLE
Branch 2.2 kubernetes

### PR DESCRIPTION
**Pull request by foxish**
Rebased onto Spark v2.2.0

/cc @apache-spark-on-k8s/contributors

### CODE REVIEW

**Comment by foxish** [comment]
Just realized I forgot to update the POMs. Will push a new change after seeing what issues crop up with integration tests (if any)

**Comment by ifilonenko** [comment]
rerun integration tests please

**Comment by ifilonenko** [comment]
LGTM

**Comment by erikerlandson** [comment]
LGTM, pending integration test completion

**Comment by foxish** [comment]
rerun integration tests please

**Comment by foxish** [comment]
(Hitting a flake. Being tracked in https://github.com/apache-spark-on-k8s/spark/issues/389)

**Comment by foxish** [comment]
rerun integration tests please

**Comment by foxish** [comment]
Will merge with a merge-commit on green. Neither squashing, nor the rebase-commit will help us here.

**Comment by ash211** [comment]
@foxish I just looked through the commits on branch-2.1-kubernetes vs branch-2.2-kubernetes and found one difference:

`branch-2.1-kubernetes` has this commit that didn't get cherry-picked onto `branch-2.2-kubernetes`:

`b139b46158 Andrew Ash 4 months ago Fix lint-check failures and javadoc8 break (#187)`

**Comment by foxish** [comment]
I see. It should have picked up all commits. Could it be that the same fix existed upstream, and hence was considered empty and omitted by the rebase?

**Comment by ash211** [comment]
Ah yes, those changes were already committed upstream in ed84cd06841.  Good to go here!

**Pull request merged**
