### PR TITLE
Prep for alpha release

### PR DESCRIPTION
**Pull request by ash211**
Re-upped version of https://github.com/apache-spark-on-k8s/spark/pull/89

### CODE REVIEW

**Comment by ash211** [comment]
# First release branch reorganization

This PR creates the new structure for release branches.  The problem we have with the current branch is that it's based off a random commit of Apache master, rather than a specific release.  This PR creates a new branch structure off the latest Apache release (2.1.0) for improved stability.

I propose we merge this branch, create another branch on the resulting commit named `branch-2.1-kubernetes-develop`, then redirect all open PRs from going into the `k8s-support-alternate-incremental` branch to going into `branch-2.1-kubernetes-develop`

This way we have two branches, the release branch for stabilization, and the dev branch for ongoing work.
- `branch-2.1-kubernetes` what we'll tag the first release off of, build docker images of, etc
- `branch-2.1-kubernetes-develop` what we'll continue merging ongoing work into

Then as we merge new PRs into `branch-2.1-kubernetes-develop`, if it's a stabilization/docs PR that we want in the release, we additionally cherry pick the commit into a new PR against `branch-2.1-kubernetes` and merge after build passes (since CR already happened on the other branch).  This follows the pattern that Apache Spark does with `master` vs `branch-2.1` vs `branch-2.0` etc.

Additionally I'd suggest that when this PR merges we use that to cut the first alpha for socialization at GCP Next.

Does this make sense @foxish @mccheah @ssuchter @lins05 @iyanuobidele @erikerlandson ?

**Comment by ssuchter** [comment]
+1 from me - thanks!

Sean

**Comment by ash211** [comment]
@kimoonkim / @cvpatel does anything jump out to you about those test failures?  Is it problematic to run them on this different branch?

**Comment by kimoonkim** [comment]
@ash211 

The Travis builds are complaining about `resource-managers/kubernetes/core/pom.xml`:

>[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.spark:spark-kubernetes_2.11:2.2.0-SNAPSHOT (/home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml) has 5 errors
[ERROR]     'dependencies.dependency.version' for com.netflix.feign:feign-core:jar is missing. @ org.apache.spark:spark-kubernetes_2.11:[unknown-version], /home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml, line 55, column 17
[ERROR]     'dependencies.dependency.version' for com.netflix.feign:feign-okhttp:jar is missing. @ org.apache.spark:spark-kubernetes_2.11:[unknown-version], /home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml, line 59, column 17
[ERROR]     'dependencies.dependency.version' for com.netflix.feign:feign-jackson:jar is missing. @ org.apache.spark:spark-kubernetes_2.11:[unknown-version], /home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml, line 63, column 17
[ERROR]     'dependencies.dependency.version' for com.netflix.feign:feign-jaxrs:jar is missing. @ org.apache.spark:spark-kubernetes_2.11:[unknown-version], /home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml, line 67, column 17
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar is missing. @ org.apache.spark:spark-kubernetes_2.11:[unknown-version], /home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/pom.xml, line 77, column 17

I remember we removed some dependencies from the top project pom.xml recently. Maybe that's the root cause?

**Comment by foxish** [comment]
+1 for the strategy. It seems like the top-level POM in this PR has the versions of those dependencies that the CI reports as missing. I'm not sure why it is reporting errors.

**Comment by foxish** [comment]
Can someone restart the integration test? Looks like minikube crashed.

<pre>
+ ./resource-managers/kubernetes/integration-tests/target/minikube-bin/linux-amd64/minikube status
minikubeVM: Does Not Exist
localkube: N/A
[PR-spark-k8s-integration-test] $ /bin/sh -xe /tmp/hudson4547463082719487775.sh
+ ./resource-managers/kubernetes/integration-tests/target/minikube-bin/linux-amd64/minikube stop
Stopping local Kubernetes cluster...
Error stopping machine:  Error loading host: minikube: Host does not exist: "minikube"
+ true
</pre>

**Comment by cvpatel** [comment]
rerun integration test please

**Comment by cvpatel** [comment]
@foxish Anyone should be able to rerun the test by adding a comment "rerun integration test please"

The minikube commands are just a red-herring, because it tries to run stop and delete whenever there is a failure. But the main issue here is the pom.xml issue.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-kubernetes_2.11:[unknown-version]: Could not find artifact org.apache.spark:spark-parent_2.11:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-docker-minimal-bundle_2.11:[unknown-version]: Could not find artifact org.apache.spark:spark-parent_2.11:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 21, column 11
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-kubernetes-integration-tests_2.11:[unknown-version]: Could not find artifact org.apache.spark:spark-parent_2.11:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-kubernetes-integration-tests-spark-jobs_2.11:[unknown-version]: Could not find artifact org.apache.spark:spark-parent_2.11:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-kubernetes-integration-tests-spark-jobs-helpers_2.11:[unknown-version]: Could not find artifact org.apache.spark:spark-parent_2.11:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
 @

**Comment by foxish** [comment]
Likely the difference in versions. 2.2.0-snapshot vs 2.1

**Comment by foxish** [comment]
Expecting https://github.com/apache-spark-on-k8s/spark/pull/178 to fix it.

**Comment by foxish** [comment]
Any commits this is missing w.r.t. k8s-support-alternate-incremental? Maybe we should do a fast-fwd if nothing that was post-alpha has merged since.

**Comment by ash211** [comment]
@foxish it has to be cherry picks not a fast forward, since a merge would pull in lots of things from apache master (the reason for the rebase).

I definitely plan on pulling in any activity merged into the k8s-support-alternate-incremental branch since this one got started

**Comment by cvpatel** [comment]
rerun integration test please

**Comment by cvpatel** [comment]
There have been intermittent issues with integration after running the full build and unit-tests on the same system... I have fixed some those issues by moving the integration tests builds to have a dedicated local maven repo... I'm thinking that the mvn install step was messing with the integration test builds...

In the last failure here it seems that the kubectl binary got uninstalled somehow... hmm not exactly sure how that happened, have reinstalled it and seems to pass after that.

**Comment by ash211** [comment]
Just pushed the latest commits from https://github.com/apache-spark-on-k8s/spark/commits/k8s-support-alternate-incremental

If these 3 Jenkins builds pass, then I'd suggest we finally merge (NOT squash and merge) this PR

**Comment by ash211** [comment]
@foxish comfortable with the merge?   NOT squash and merge?

**Comment by foxish** [comment]
Yes, that would be best, given that we'll have the dev branch off of this one, and want history as it is.

**Comment by ash211** [comment]
Great, thanks for everyone's contributions helping diagnose test failures!

**Pull request merged**
