### PR TITLE
Removing deprecated configuration

### PR DESCRIPTION
**Pull request by foxish**
PTAL @liyinan926 

cc @mccheah @erikerlandson 
**Note**: this needs a release-note!

### CODE REVIEW

**Comment by mccheah** [comment]
Submission steps orchestrator test appears to be broken from the build. Otherwise the change itself LGTM.

**Comment by liyinan926** [comment]
Seems some test suites need  to be fixed as well. Otherwise, LGTM.

**Comment by mccheah** [comment]
Oh these configurations are still referenced in the documentation as well - please remove from there.

**Comment by foxish** [comment]
Superseded by https://github.com/apache-spark-on-k8s/spark/pull/503

**Pull request closed without merging**
