### PR TITLE
[WIP] Kimoon's extra commits atop PR 414

### PR DESCRIPTION
**Pull request by kimoonkim**
To share extra commits on top of #141, mostly with @ifilonenko. Please see my commits from Aug 11 for the diff between this and #414, namely:

> @kimoonkim	Include HADOOP_CONF_DIR in SPARK_CLASSPATH			e38c981
 @kimoonkim	Support extra JVM options in executors			c33f7b4
 @kimoonkim	Support SPARK_USER			a2c31de
 @kimoonkim	Allow spark.hadoop keys in executor JVM options			cc6aa4b
 @kimoonkim	Automatically set simple authn in driver and executor pods			62a854b

This successfully runs `DFSReadWriteTest` against my single node Kerberized HDFS pod.
```
$ klist
Ticket cache: KCM:502
Default principal: kimoonkim@PEPPERDATA.COM

Valid starting       Expires              Service principal
08/11/2017 09:54:01  08/12/2017 09:54:01  krbtgt/PEPPERDATA.COM@PEPPERDATA.COM
        renew until 08/11/2017 09:54:01

$ HADOOP_CONF_DIR=/usr/local/hadoop/conf /usr/local/spark-on-k8s/bin/spark-submit --class org.apache.spark.examples.DFSReadWriteTest --conf spark.app.name=spark-dfsrw --conf spark.kubernetes.kerberos=true --conf spark.hadoop.fs.defaultFS=hdfs://kube-n1:32560 --conf spark.hadoop.dfs.namenode.kerberos.principal=hdfs/cdh58-kimoon-rc-dwvck@PEPPERDATA.COM local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.3.0-SNAPSHOT.jar /etc/hosts /tmp/hosts
...
2017-08-11 17:03:10 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state:
         pod name: spark-dfsrw-1502496160933-driver
         namespace: default
         labels: spark-app-selector -> spark-e82c4e83cbba468ba1d3abe4701c2eed, spark-role -> driver
         pod uid: 905e2115-7ef1-11e7-9e51-02f2c310e88c
         creation time: 2017-08-12T00:02:43Z
         service account name: default
         volumes: hadoop-properties, hadoop-secret, default-token-2jnd3
         node name: kube-n1.pepperdata.com
         start time: 2017-08-12T00:02:43Z
         container images: docker:5000/spark-driver:custom-kimoon-0811-6
         phase: Succeeded
         status: [ContainerStatus(containerID=docker://dc1fbe599aab561eb07a5ed843912f4291e15a358ed09e2f328d2f4522a44560, image=docker:5000/spark-driver:custom-kimoon-0811-6, imageID=docker-pullable://docker:5000/spark-driver@sha256:6896b178f69713328b3ad9c2db221ca1fa6089c0a277ceb5c7ecbb43f4bdc79d, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://dc1fbe599aab561eb07a5ed843912f4291e15a358ed09e2f328d2f4522a44560, exitCode=0, finishedAt=2017-08-12T00:03:09Z, message=null, reason=Completed, signal=null, startedAt=2017-08-12T00:02:53Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})]
2017-08-11 17:03:10 INFO  LoggingPodStatusWatcherImpl:54 - Container final statuses:


         Container name: spark-kubernetes-driver
         Container image: docker:5000/spark-driver:custom-kimoon-0811-6
         Container state: Terminated
         Exit code: 0
2017-08-11 17:03:10 INFO  Client:54 - Application spark-dfsrw finished.

$ kubectl logs spark-dfsrw-1502496160933-driver | tail
2017-08-12 00:03:08 INFO  KubernetesClusterSchedulerBackend:54 - Closing kubernetes client
2017-08-12 00:03:08 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2017-08-12 00:03:08 INFO  MemoryStore:54 - MemoryStore cleared
2017-08-12 00:03:08 INFO  BlockManager:54 - BlockManager stopped
2017-08-12 00:03:08 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped
2017-08-12 00:03:08 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2017-08-12 00:03:08 INFO  SparkContext:54 - Successfully stopped SparkContext
Success! Local Word Count (20) and DFS Word Count (20) agree.
2017-08-12 00:03:08 INFO  ShutdownHookManager:54 - Shutdown hook called
2017-08-12 00:03:08 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-4f3479c2-7e23-45e9-a8aa-869849e560ed

$ kubectl exec -it cdh58-kimoon-rc-dwvck -- hadoop fs -ls /tmp/hosts
Found 1 items
drwxr-xr-x   - kimoonkim supergroup          0 2017-08-12 00:03 /tmp/hosts/dfs_read_write_test
``` 

Before running the job, I signed on with Kerberos by doing `kinit` on my Macbook.
```
$ klist
Ticket cache: KCM:502
Default principal: kimoonkim@PEPPERDATA.COM

Valid starting       Expires              Service principal
08/11/2017 09:54:01  08/12/2017 09:54:01  krbtgt/PEPPERDATA.COM@PEPPERDATA.COM
        renew until 08/11/2017 09:54:01

$ cat /etc/krb5.conf
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = PEPPERDATA.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 PEPPERDATA.COM = {
  kdc = kube-n1:31326
  admin_server = kube-n1:31326
 }

[domain_realm]
 .pepperdata.com = PEPPERDATA.COM
 pepperdata.com = PEPPERDATA.COM

$ cat /usr/local/hadoop/conf/core-site.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <property>
    <name>hadoop.security.authentication</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hadoop.security.authorization</name>
    <value>true</value>
  </property>
</configuration>
```

### CODE REVIEW

**Comment by ifilonenko** [comment]
I will add a commit, and if you okay it, I will merge the 414 PR into the hdfs branch, at which point please cherry pick the commits to handle the use case. specifically, commits starting from c33f7b4

**Comment by kimoonkim** [comment]
@ifilonenko SGTM. I see #414 has my changes and it passes integration tests. Awesome and thanks!

**Comment by erikerlandson** [comment]
@kimoonkim does that mean we can safely close this PR?

**Comment by kimoonkim** [comment]
Yes, I think we can close this. @ifilonenko?

**Comment by ifilonenko** [comment]
Yes, closing PR now

**Pull request closed without merging**
