### PR TITLE
Adding legacyHostIP to the list of IPs we look at

### PR DESCRIPTION
**Pull request by foxish**
Should fix minikube issue in https://github.com/apache-spark-on-k8s/spark/issues/112

### CODE REVIEW

**Comment by mccheah** [comment]
Looks ok to fix Minikube, although it would be good to follow up on the Minikube side to see why it's returning the new IP type in the first place. @foxish any idea why that is the case now?

**Review by mccheah — APPROVED** [review]
Looks fine but would like to know why this started showing up in this Minikube version. ExternalIP seems like the correct classification. Plus if a node advertises both an ExternalIP and a LegacyHostIP, should we pick only one or the other, or pick both?

**Comment by foxish** [comment]
It is deprecated, so, Minikube should move away from it and set the External/Internal IP. I'm not sure why they're still setting that parameter instead. 
If both are provided, I think the order is ExternalIP first, then LegacyHostIP.

**Comment by kimoonkim** [comment]
We have an on-premiss kubernetes 1.4 cluster that also has LegacyHostIP/InternalIP. So this fix helps us.

**Pull request merged**
