### PR TITLE
Add kubernetes profile to travis CI yml file

### PR DESCRIPTION
**Pull request by kimoonkim**
@ssuchter @foxish @ash211 

The current .[travis.yml](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/.travis.yml) file does not use the kubernetes build profile. This change adds the profile so the CI builds will compile kubernetes code.

Note this may make Travis unhappy again. If fixes are trivial, I can include them in this pull request too.

### CODE REVIEW

**Review by ash211 — APPROVED** [review]
Looks right to me, let's hope this passes.  We could consider dropping `-Pmesos` and `-Pyarn` if builds take too long

**Comment by foxish** [comment]
I agree, we can probably drop -Pmesos and -Pyarn. In future, we also want to run our own integration tests and ensure they're not flaky. Not sure yet how we can make minikube fit with travis though.

**Comment by mccheah** [comment]
I'd avoid running the integration tests right this moment since they're unstable, and we should get them to a better place. But yes, we should execute the tests in the near future.

**Comment by kimoonkim** [comment]
The Travis [build](https://travis-ci.org/apache-spark-on-k8s/spark/builds/191783715) has failed with line length checks.

```
error file=/home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/rest/kubernetes/CompressionUtils.scala message=File line length exceeds 100 characters line=41
error file=/home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/rest/kubernetes/CompressionUtils.scala message=File line length exceeds 100 characters line=42
error file=/home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/rest/kubernetes/CompressionUtils.scala message=File line length exceeds 100 characters line=43
error file=/home/travis/build/apache-spark-on-k8s/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/rest/kubernetes/CompressionUtils.scala message=File line length exceeds 100 characters line=44
```

I'll see if I can fix them.

**Comment by kimoonkim** [comment]
Fixed the long lines. Hope it passes now.

@ash211 and @foxish, I'll experiment with dropping -Pmesos and -Pyarn on my personal fork/travis.

**Comment by kimoonkim** [comment]
The build passes now.

I experimented with  dropping -Pmesos and -Pyarn. It does not save build time much. Note travis runs JDK7 and JDK8 in parallel. Turn around time is the slowest of the two.
- drop Pmesos and Pyarn ([link](https://travis-ci.org/kimoonkim/spark/builds/191824434))
  - oraclejdk7: 27 min 30 sec
  - oraclejdk8: 25 min 14 sec
- keep Pmesos and Pyarn ([link](https://travis-ci.org/kimoonkim/spark/builds/191819623))
  - oraclejdk7: 27 min 57 sec
  - oraclejdk8: 26 min 12 sec

**Comment by foxish** [comment]
Perfect. Thanks for carrying out the experiment as well. All green. Merging.

**Pull request merged**
