### PR TITLE
Rename package to k8s

### PR DESCRIPTION
**Pull request by foxish**
/xref https://github.com/apache-spark-on-k8s/spark/pull/492#discussion_r139560316

cc @apache-spark-on-k8s/contributors

### CODE REVIEW

**Comment by foxish** [comment]
Let's merge this after the new 2.2 release.

**Review by mccheah — APPROVED** [review]
LGTM - also good that the non-code references were corrected, such as the Dockerfiles.

**Comment by foxish** [comment]
On second thought, maybe we should include this in the release. It will help folks migrate to the upstream one without jumping through hoops. WDYT @mccheah @liyinan926

**Comment by liyinan926** [comment]
@foxish I think this should go into the new release. It's better doing it earlier than later. It makes the upcoming upstreaming PRs easier to go by.

**Comment by foxish** [comment]
Agreed. It's low-risk since the failures would have been fairly obvious.

**Comment by ifilonenko** [comment]
@varunkatta @ssuchter The Jenkins environment needs to be updated since the commands had a wildcard on `deploy.kubernetes.*` which has been changed to `deploy.k8s.*`

**Comment by foxish** [comment]
Good catch @ifilonenko! We should do this asap. Manually verifying that integration tests are okay.

**Comment by ssuchter** [comment]
I just saw this thread. I’m not sure what updates I’d need to make. Also,
I’m mention - if anyone needs a jenkins UI login that doesn’t have it, just
let me know.

Sean

On September 24, 2017 at 5:44:40 PM, Anirudh Ramanathan (
notifications@github.com) wrote:

Good catch @ifilonenko <https://github.com/ifilonenko>! We should do this
asap. Manually verifying that integration tests are okay.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/pull/497#issuecomment-331751697>,
or mute the thread

**Comment by foxish** [comment]
The integration tests run:

> ./build/mvn -B -Dmaven.repo.local=/home/jenkins/.m2/pr_intg_test_repo clean integration-test -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite


We need to change the last argument to `-DwildcardSuites=org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite`.
Can you create a login/pass for me and Ilan? Then we could probably do this directly.

**Comment by ssuchter** [comment]
I made the change already. I see that you both have usernames on the
jenkins already - I’ll contact you on slack about that.

Sean


On September 25, 2017 at 8:48:49 AM, Anirudh Ramanathan (
notifications@github.com) wrote:

The integration tests run:

./build/mvn -B -Dmaven.repo.local=/home/jenkins/.m2/pr_intg_test_repo clean
integration-test -Pkubernetes -Pkubernetes-integration-tests -pl
resource-managers/kubernetes/integration-tests -am -Dtest=none
-DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite

We need to change the last argument to
-DwildcardSuites=org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite
.
Can you create a login/pass for me and Ilan? Then we could probably do this
directly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/pull/497#issuecomment-331924544>,
or mute the thread

**Pull request merged**
