### PR TITLE
Add proxy configuration to retrofit clients.

### PR DESCRIPTION
**Pull request by mccheah**
Similar to what we did for `HttpClientUtil` in the first version of submission. This allows `http.proxy` and `https.proxy` configurations to take effect when the submission client contacts the resource staging server. Note that this currently will not have any effect on when pods contact the resource staging server to download the dependencies, since the init-container JVM options are not set by any components at the moment.

### CODE REVIEW

**Comment by ash211** [comment]
@mccheah looks like the build doesn't like your import ordering:

`
error file=/home/jenkins/workspace/PR-spark-k8s-full-build/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/rest/kubernetes/RetrofitClientFactory.scala message=import.ordering.wrongOrderInSelector.message line=33 column=24
`

**Comment by ash211** [comment]
Is there a good way to test this?

**Comment by mccheah** [comment]
Not easily - we could inject providers for the okhttp and retrofit related components so that we can put mocks in front of them, but such tests wouldn't be that useful.

**Comment by ash211** [comment]
rerun full build please

**Comment by ash211** [comment]
Beginning local testing, will merge if passes

**Comment by ash211** [comment]
Local testing was good, will merge when test passes

**Pull request merged**
