### PR TITLE
Add support for fetching application dependencies from HDFS

### LINKED ISSUE #584: Add support for fetching application dependencies from HDFS
To add support for fetching application dependencies from HDFS, we need to mount HADOOP_CONF_DIR to init container.

Usage example:

```
$ export HADOOP_CONF_DIR=pwd/hadoopconf

$ bin/spark-submit --deploy-mode cluster --class org.apache.spark.examples.SparkPi 
--master k8s://http://localhost:8080 --kubernetes-namespace default
--conf spark.executor.instances=5 
--conf spark.app.name=spark-pi
--conf spark.kubernetes.driver.docker.image=jungong/spark-driver:hdfs
--conf spark.kubernetes.executor.docker.image=jungong/spark-executor:hdfs
--conf spark.kubernetes.initcontainer.docker.image=jungong/spark-init:hdfs
--conf spark.kubernetes.initcontainer.inannotation=true
--conf spark.kubernetes.docker.image.pullPolicy=Always
hdfs://hdfsCluster/spark/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

### PR DESCRIPTION
**Pull request by hex108**
## What changes were proposed in this pull request?

Fix #584 

## How was this patch tested?

Manual tests as in #584.

### CODE REVIEW

**Comment by liyinan926** [comment]
We already have `org.apache.spark.deploy.k8s. HadoopConfBootstrapImpl` that has the logic for mounting the `HADOOP_FILE_VOLUME` into a container.

**Comment by hex108** [comment]
hi @liyinan926 ,  if I understand correctly, HadoopConfBootstrapImpl is used to mount Hadoop conf to driver/executor pod's main container, and now we only mount Hadoop conf to driver/executor container. However we also need mount it to init container to fetch HDFS dependencies.

**Comment by liyinan926** [comment]
@hex108 Yes, it is for mounting the Hadoop conf ConfigMap into the driver and executor containers. My point is the logic is duplicated, so should be extracted out and shared. For example, we have `MountSecretBootstrap` that is shared for mounting secrets into the main and init containers in both the driver and executor pods. I would suggest renaming `MountHadoopConfStep ` to something that has `Bootstrap` in the name and using it in places where mounting the ConfigMap is needed.

**Comment by hex108** [comment]
@liyinan926 Thanks, I get it now. I'll refactor it.

**Comment by ifilonenko** [comment]
If it is alright, I am currently working on integration tests for hdfs (secure and non), after a few LGTM and after passing the tests that I write, we can merge this PR, after resolving comments. Want to mitigate changes to HDFS until there are integration test in place to validate the logic e2e.

Furthermore this PR is missing unit tests, can you please add? 

Thanks for this work!

**Pull request closed without merging**
