### PR TITLE
Remove okhttp from top-level pom

### PR DESCRIPTION
**Pull request by foxish**
Fix https://github.com/apache-spark-on-k8s/spark/issues/165

I'm having issues running the integration tests but they seemed to pass once.
@cvpatel PTAL

### CODE REVIEW

**Comment by foxish** [comment]
Confirmed that the fix works

**Comment by ash211** [comment]
It will be interesting to see if this does indeed fix the integration tests in Travis.  @cvpatel is there an available link to the Jenkins instance you mentioned or is that part of the larger issue https://github.com/apache-spark-on-k8s/spark/issues/158 ?

**Comment by cvpatel** [comment]
Just got the public access working about an hour ago... it is:
http://66.128.149.237:8080/job/PR-apache-spark-on-k8s_spark/

Once this fix is in, we'll enable adding the messages to the PRs directly.

For some reason I think the failure leaves the system in a weird state, and requires it be run again...

**Comment by cvpatel** [comment]
rerun integration test please

**Comment by foxish** [comment]
@cvpatel, does it rebuild the minikube cluster and create new docker images each time? I think that needs it to run pre-integration-test first.

**Comment by cvpatel** [comment]
It runs the following command, which should do it?
`./build/mvn -B clean integration-test -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite`

I couldn't even start minikube on the system manually; I have added some cleanup steps in case of failures to stop and delete minikube explicitly, which should hopefully be enough. Trying once more .

**Comment by cvpatel** [comment]
rerun integration test please

**Comment by cvpatel** [comment]
Looks good now! http://66.128.149.237:8080/job/PR-apache-spark-on-k8s_spark/22/

**Comment by ash211** [comment]
Nice!  Thanks for the assist with testing @cvpatel and for the fix @foxish !

**Pull request merged**
