### PR TITLE
Use tini in Docker images.

### LINKED ISSUE #317: Use tini to prevent JVM as pid1 errors
https://github.com/krallin/tini

quick summary is running JVMs as pid1 in dockerfiles cause problems -- search for `Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)` to see examples

### PR DESCRIPTION
**Pull request by mccheah**
Closes #317.

### CODE REVIEW

**Review by ash211 — APPROVED** [review]
LGTM -- @foxish did you have any questions about this since you were asking about it during the weekly video call today?

**Comment by foxish** [comment]
@tnachen PTAL

**Comment by erikerlandson** [comment]
Is there a reason it's using tini as an entrypoint in some, but `exec /sbin/tini ...` in others?

**Comment by mccheah** [comment]
The `exec` ones have to do more complex bash environment variable substitution at execution time, so those more comfortably fit in the `exec` form of the Docker command. It would be good to unify these, but for another time.

**Comment by erikerlandson** [comment]
This is a bit tangential and not a bug, but multiple `RUN` statements can be combined to reduce the number of image layers:

```
RUN apk upgrade --update
RUN apk add --update bash tini
RUN mkdir -p /opt/spark
RUN touch /opt/spark/RELEASE
```

Can be combined like:

```
RUN apk upgrade --update && \
    apk add --update bash tini && \
    mkdir -p /opt/spark && \
    touch /opt/spark/RELEASE
```

**Comment by ash211** [comment]
@erikerlandson what are the advantages to having fewer image layers?

**Comment by tnachen** [comment]
LGTM, but I also suggest having few layers. It's generally a best practice to have fewer layers, as the more layers you have the more work registry/daemon/client will have to do to download and manage.
Also depending on the filesystem you end up using with Docker, fewer layers could also help performance as some filesystems requires copying and traversing layers on writes/reads.

**Comment by erikerlandson** [comment]
Another potential benefit to consolidated `RUN` is you can do file cleanup in the same layer, which is another way to decrease image size.  This post describes some examples:

https://blog.codeship.com/reduce-docker-image-size/

I don't quite follow the `exec` distinction, but I have no doubt it solves the pid problem either way.

**Comment by ash211** [comment]
Let's squash those layers in a separate PR -- it definitely sounds like a good idea and I don't see a downside to it.

https://github.com/apache-spark-on-k8s/spark/issues/323

**Pull request merged**
