### PR TITLE
Fix lint-check failures and javadoc8 break

### PR DESCRIPTION
**Pull request by ash211**
(cherry picked from commit ed84cd068419550b4a1b88a41e73f1870c3967e4)

### CODE REVIEW

**Comment by foxish** [comment]
@ash211 Looks like the import shouldn't be removed. Can we revert that particular change in a new commit?

**Comment by ash211** [comment]
Hmm, looks like Travis and Jenkins both failed in the same `SparkContextSuite` though on different tests..

[Jenkins](http://spark-k8s-jenkins.pepperdata.org:8080/job/PR-spark-k8s-unit-tests/15/consoleFull#199335566104b09c7b-0d94-4ce5-8a08-8f343248b3d8):

```
- addJar can be called twice with same file in local-mode (SPARK-16787)
- addFile can be called twice with same file in local-mode (SPARK-16787)
- addJar can be called twice with same file in non-local-mode (SPARK-16787)
- addFile can be called twice with same file in non-local-mode (SPARK-16787) *** FAILED ***
  java.lang.IllegalStateException: Shutdown hooks cannot be modified during shutdown.
  at org.apache.spark.util.SparkShutdownHookManager.add(ShutdownHookManager.scala:195)
  at org.apache.spark.util.ShutdownHookManager$.addShutdownHook(ShutdownHookManager.scala:153)
  at org.apache.spark.storage.DiskBlockManager.addShutdownHook(DiskBlockManager.scala:145)
  at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:51)
  at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:82)
  at org.apache.spark.SparkEnv$.create(SparkEnv.scala:349)
  at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:174)
  at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:432)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:145)
  ...
```

[Travis](https://travis-ci.org/apache-spark-on-k8s/spark/jobs/211571251)

```
- addJar can be called twice with same file in local-mode (SPARK-16787)
- addFile can be called twice with same file in local-mode (SPARK-16787)
- addJar can be called twice with same file in non-local-mode (SPARK-16787)
- addFile can be called twice with same file in non-local-mode (SPARK-16787)
- Cancelling job group should not cause SparkContext to shutdown (SPARK-6414) *** FAILED ***
  java.lang.NullPointerException:
  at org.apache.spark.SparkContextSuite$$anonfun$14.apply$mcV$sp(SparkContextSuite.scala:303)
  at org.apache.spark.SparkContextSuite$$anonfun$14.apply(SparkContextSuite.scala:293)
  at org.apache.spark.SparkContextSuite$$anonfun$14.apply(SparkContextSuite.scala:293)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:68)
  ...
```

Could this suite be full of flaky tests?

**Comment by foxish** [comment]
rerun unit tests please

**Comment by foxish** [comment]
@cvpatel, how do we trigger the unit tests again?

**Comment by foxish** [comment]
Oh nvm, it worked now.

**Comment by ash211** [comment]
And success that time!  It passed the Jenkins checks but not the Travis ones (which I just restarted)

@foxish are you comfortable merging this now as an incremental improvement to the `prep-for-alpha-release` branch as we work through these testing issues?

**Comment by foxish** [comment]
I think we can stop looking at travis at this point, due to the memory errors. Thanks for fixing this @ash211. Do you think we can now merge https://github.com/apache-spark-on-k8s/spark/pull/177 ?

**Comment by ash211** [comment]
Hoping so, let's continue discussion there

**Pull request merged**
