### PR TITLE
[WIP] Extract constants

### LINKED ISSUE #47: Pull kubernetes config keys out into a separate class
Something like the below class for kubernetes would be good for making sure we're not missing config keys in the docs, plus generally pull all config keys into one place which seems like a good idea.

https://github.com/apache/spark/blob/v2.1.0/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala

### PR DESCRIPTION
**Pull request by mccheah**
Closes #47.

### CODE REVIEW

**Comment by mccheah** [comment]
Still more to do but this illustrates the general concept. Note this is an addition to #30 because #30 introduces a number of additional parameters and constants that I wanted to capture in this refactor.

**Comment by mccheah** [comment]
Ah we have to change the base branch - we merged the other thing first!

**Comment by foxish** [comment]
@mccheah Sorry! I didn't realize this one was dependent on the nodeport PR.

**Comment by foxish** [comment]
It is possible to change the branch that it targets from the github UI IIRC.

**Comment by mccheah** [comment]
Good call

**Comment by mccheah** [comment]
Something is weird - going to start over again, apologize if you started reviewing.

**Pull request closed without merging**
