### PR TITLE
Refactor for Hadoop conf related code

### PR DESCRIPTION
**Pull request by hex108**
## What changes were proposed in this pull request?
When doing some refactor for #585  , I find that it will help a lot to do some refactor for Hadoop conf related code. It might be better to split a separate and small PR for it.

(Please fill in changes proposed in this fix)

* Add `HadoopConfUtils`
* Remove unused `hadoopUGI` from `HadoopConfBootstrapImpl`.

## How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by hex108** [comment]
@liyinan926 PTAL. Thanks!

**Comment by hex108** [comment]
**Integration Test** error is environment related.

**Comment by liyinan926** [comment]
rerun integration tests please

**Comment by liyinan926** [comment]
LGTM. Will merge once integration tests pass.

**Review by liyinan926 — APPROVED** [review]

**Comment by ifilonenko** [comment]
Thank you for your work on this!

**Comment by hex108** [comment]
Thanks!

**Pull request merged**
