### PR TITLE
Exclude flaky ExternalShuffleServiceSuite from Travis

### PR DESCRIPTION
**Pull request by kimoonkim**
To help #178 get in shape.

cc @foxish

### CODE REVIEW

**Comment by foxish** [comment]
rerun integration test please

**Comment by foxish** [comment]
@kimoonkim, looks like one of the travis builds exited with memory errors again.

**Comment by cvpatel** [comment]
It seem unit-tests are passing now, but there is still a [checkstyle failure](http://spark-k8s-jenkins.pepperdata.org:8080/job/PR-spark-k8s-full-build/2/consoleFull#1836529423da7c09f2-35f0-40f7-bee4-9c924862e95b)

**Comment by cvpatel** [comment]
rerun integration test please

**Comment by ash211** [comment]
Checkstyle failure was fixed upstream in https://github.com/apache/spark/commit/ed84cd06841

**Comment by ash211** [comment]
Will merge this as an incremental improvement and open a new PR cherry picking that commit

Edit: https://github.com/apache-spark-on-k8s/spark/pull/187

**Pull request merged**
